spring:
  application:
    name: item-service
  cloud:
    config:
      override-none: true dsfgergherh
      override-none: true d23456465
      override-none: true 654646h

server:
  port: 8001    
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka
