spring:
  application:
    name: item-service
  cloud:
    config:
      override-none: true true
#流浪

server:
  port: 8001    
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka
